services:
  redis:
    image: redis:7.4.2-alpine
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASS} --port ${REDIS_PORT}
    expose:
      - "${REDIS_PORT}"
    volumes:
      - redis:/data
    networks:
      - backend

  server:
    build: ./server/
    restart: always
    depends_on:
      - redis
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    networks:
      - backend

  clientapp:
    build: ./clientapp/
    restart: always
    depends_on:
      - server
    networks:
      - backend

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - server
      - clientapp
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend
volumes:
  redis:
    driver: local

networks:
  backend:
    driver: bridge
